name: Trigger tests on pull request

on:
    [pull_request]:
    
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Placeholder
          run: |
            echo "Will add code checks here in next challenge"
