name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  job1:
    name: experiment
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml --resource-group rg-mlstream-llm --workspace-name aml-mlstream-llm --stream
  job2:
    needs: job1 
    name: production
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job_prod.yml --resource-group rg-mlstream-llm --workspace-name aml-mlstream-llm
